config/routes.rb
Rocksaga::Application.routes.draw do
  root :to => "game#index"
  
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match '/signin' => 'sessions#new', :as => :signin, via: [:get, :post]
  match '/signout' => 'sessions#destroy', :as => :signout, via: [:get, :post]
  match '/auth/failure' => 'sessions#failure', via: [:get, :post]

  resources :users, :only => [:index, :show]
  resources :scores
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/score.rb
class Score < ActiveRecord::Base

  attr_accessible :name, :score

  validates_presence_of :name
  validates_presence_of :score

  def self.where_top(limit = 10)
    order("#{table_name}.score DESC")
    .limit(limit)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  attr_accessible :role_ids, :as => :admin
  attr_accessible :provider, :provider_id, :name, :email
  validates_presence_of :name

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.provider_id = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

  def update_credentials(auth)
    if auth['credentials']
      self.provider_access_token = auth['credentials']['token']
      self.provider_access_token_secret = auth['credentials']['secret']
      self.save!
    end
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  protect_from_forgery

  private

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/authentication.rb
module Authentication

  def sign_in(user) 
    # Reset the session after successful login, per
    # 2.8 Session Fixation – Countermeasures:
    # http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    request.reset_session
    session[:user_id] = user.id
  end

  def sign_out
    request.reset_session
  end

  def authenticate_user!
    if !current_user
      redirect_to root_url, :alert => 'You need to sign in for access to this page.'
    end
  end

  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue Exception => exception
      Rails.logger.error exception
      nil
    end
  end

  def current_user_is_admin?
    @current_user_is_admin ||= current_user_signed_in? && current_user.has_role?(:admin)
  end

  def current_user_signed_in?
    return true if current_user
  end

  def verify_admin
    redirect_to root_url unless current_user.has_role? :admin
  end

  def self.included method 
    return unless method < ActionController::Base
    method.helper_method :correct_user?, :current_user, :current_user, :current_user_is_admin?, :current_user_signed_in?, :sign_in # , :any_other_helper_methods

  end

end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    @users = User.all
    @score = Score.new
    @top_score = Score.where_top.first
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.where_top.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/1/edit
  def edit
    @top_score = Score.where_top.first
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)
    @top_score = Score.where_top.first

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully saved.' }
        format.json { render action: 'show', status: :created, location: @score }
      else
        format.html { render action: 'new' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:name, :score)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/twitter'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :provider_id => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    user.update_credentials(auth)
    sign_in user
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    sign_out
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    params[:message] ||= ''
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/game/_board.html.erb
<div id="game-board" data-board>
  Game board goes here
</div>

app/views/game/index.html.erb
<h1>
  The Saga Begins
</h1>

<%= render 'board' %>

<%= render '/scores/form' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <%= link_to 'Rock Saga', root_path %>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li>
  <%= link_to 'New Game', root_path, :class => 'button' %>
</li>
<li>
  <%= link_to 'Top Scores', scores_path %>
</li>
<% if current_user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>
<% if current_user_signed_in? %>
  <li>
  <%= link_to 'Logout', signout_path %>
  </li>
<% else %>
  <li>
  <%= link_to 'Login', signin_path %>
  </li>
<% end %>
<% if current_user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <li>
    <%= link_to 'Admin', users_path %>
    </li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rock Saga" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rock Saga" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/scores/_form.html.erb
<%= form_for(@score, :html => {'data-scoreboard' => 'data-scoreboard'}) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% unless @top_score.nil? %>
      <%= f.label :score, "Score (current best: #{@top_score.score})" %>
    <% else %>
      <%= f.label :score %>
    <% end %>
    
    <%= f.text_field :score, :readonly => true %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>  

  <div class="actions">
    <%= f.submit "Submit Score", :class => 'button' %>
    <%= link_to "Top Scores", scores_path, :class => 'button secondary' %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<h1>Top Scores</h1>

<ol>
  <% @scores.each do |score| %>
    <li>
      <h2>
        <b><%= score.name %>:</b>
        <%= score.score %>
      </h2>
    </li>
  <% end %>
</ol>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<h2>
  <b><%= @score.name %>:</b>
  <%= @score.score %>
</h2>

<%= link_to "Top Scores", scores_path, :class => 'button' %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= collection_select :user, :role_ids, Role.all, :id, :name, checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.submit "Sign in" %>
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>